version: "3.8"

services:
  database:
    container_name: db
    image: postgres:13.4-alpine
    restart: always
    user: postgres
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - postgres

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - postgres

volumes:
  pgdata:
  api:


networks:
  postgres:
